import { generateCatalogue } from '../seed/catalogue/generate.js';
import { flattenTree, loadTree } from '../seed/tree.js';
const nodes = flattenTree(loadTree());
const t0 = Date.now();
const cat = generateCatalogue(nodes);
const count = (id: string) => cat.products.filter((p) => p.nodeIds.has(id)).length;
const subs = nodes.filter((n) => n.type === 'subcategory');
const cats = nodes.filter((n) => n.type === 'category');
console.log('products', cat.products.length, 'variants', cat.products.reduce((s, p) => s + p.variants.length, 0), 'brands', cat.brands.length, 'curated', cat.curated.length, 'ms', Date.now() - t0);
console.log('subcats < 6:', subs.filter((s) => count(s.id) < 6).map((s) => `${s.id}=${count(s.id)}`));
console.log('categories < 48:', cats.filter((c) => count(c.id) < 48).map((c) => `${c.id}=${count(c.id)}`));
for (const s of nodes.filter((n) => n.type === 'section')) console.log(s.id, count(s.id), 'owned', cat.products.filter((p) => p.primarySectionId === s.id).length);
console.log('sample:', cat.products.slice(0, 3).map((p) => `${p.brand} | ${p.name} | ${p.subtitle} | ₹${p.variants[0]!.sellingPrice / 100}/₹${p.variants[0]!.mrp / 100}`));
console.log('oos products', cat.products.filter((p) => p.variants.every((v) => v.onHand === 0)).length, 'bestSellers', cat.products.filter((p) => p.bestSeller).length, 'bankOffer', cat.products.filter((p) => p.bankOfferEligible).length);
import { generateReviews } from '../seed/catalogue/reviews.js';
const reviews = generateReviews(cat.products);
const withReviews = new Set(reviews.map((r) => r.productId)).size;
console.log('reviews', reviews.length, 'products with reviews', withReviews, 'with text', reviews.filter((r) => r.text).length);
const avgs = cat.products.map((p) => { const rs = reviews.filter((r) => r.productId === p.id); return rs.length ? rs.reduce((a, r) => a + r.rating, 0) / rs.length : null; }).filter((x): x is number => x !== null);
console.log('avg rating range', Math.min(...avgs).toFixed(1), '-', Math.max(...avgs).toFixed(1), 'mean', (avgs.reduce((a, b) => a + b, 0) / avgs.length).toFixed(2));
